# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x19\n\tUserReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2<\n\x0bUserService\x12-\n\x07GetUser\x12\x11.user.UserRequest\x1a\x0f.user.UserReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=20
  _globals['_USERREQUEST']._serialized_end=51
  _globals['_USERREPLY']._serialized_start=53
  _globals['_USERREPLY']._serialized_end=78
  _globals['_USERSERVICE']._serialized_start=80
  _globals['_USERSERVICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
