name: sqli-basics-lab

services:
  web:
    build: .
    container_name: sqli-basics-web
    ports:
      - "7104:80"
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /var/log/apache2
      - /var/run/apache2
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    restart: "no"
    user: "1000:1000"

  db:
    image: mysql:8.0
    container_name: sqli-basics-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab_db
      MYSQL_USER: labuser
      MYSQL_PASSWORD: labpass
    restart: "no"
